\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename srlog2doc.info
@settitle srlog2 documentation
@setchapternewpage off
@paragraphindent 5
@footnotestyle end
@c %**end of header

@ifinfo
Copyright @copyright{} 2006 Bruce Guenter
@end ifinfo

@titlepage
@title srlog2 documentation
@author Bruce Guenter
@subtitle @today{}
@end titlepage

@ifinfo
This document explains ...
@end ifinfo

@node Top, Introduction, (dir), (dir)

@menu
* Introduction::                
* Design Notes::                
* Configuration::               
@end menu

@c ****************************************************************************
@node Introduction, Design Notes, Top, Top
@chapter Introduction

@c ****************************************************************************
@node Design Notes, Configuration, Introduction, Top
@chapter Design Notes

@menu
* Use Sender Names::            
@end menu

@node Use Sender Names,  , Design Notes, Design Notes
@section Sender Names

The first design for srlog used IP addresses exclusively to identify
senders in the receiver program.  This however led to problems when
the IP address on a sender changed.  In particular, when a sender had
multiple IP addresses, the kernel would make an arbitrary choice of
which one to use for sending, and that could confuse the
receiver. Switching from strictly IPs to names has the additional
benefit of allowing support for roaming senders.

@c ****************************************************************************
@node Configuration,  , Design Notes, Top
@chapter Configuration

@c ****************************************************************************
@contents

@bye
